# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.49.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.api.hosting_node_js_api import HostingNodeJSApi


class TestHostingNodeJSApi(unittest.TestCase):
    """HostingNodeJSApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HostingNodeJSApi()

    def tearDown(self) -> None:
        pass

    def test_analyse_failed_node_js_build_v1(self) -> None:
        """Test case for analyse_failed_node_js_build_v1

        Analyse failed Node.js build
        """
        pass

    def test_clear_node_js_runtime_logs_v1(self) -> None:
        """Test case for clear_node_js_runtime_logs_v1

        Clear Node.js runtime logs
        """
        pass

    def test_get_node_js_build_details_v1(self) -> None:
        """Test case for get_node_js_build_details_v1

        Get Node.js build details
        """
        pass

    def test_get_node_js_build_logs_v1(self) -> None:
        """Test case for get_node_js_build_logs_v1

        Get NodeJS build logs
        """
        pass

    def test_get_node_js_build_settings_from_archive_v1(self) -> None:
        """Test case for get_node_js_build_settings_from_archive_v1

        Get Node.js build settings from archive
        """
        pass

    def test_get_node_js_build_settings_v1(self) -> None:
        """Test case for get_node_js_build_settings_v1

        Get Node.js build settings
        """
        pass

    def test_get_node_js_runtime_logs_v1(self) -> None:
        """Test case for get_node_js_runtime_logs_v1

        Get Node.js runtime logs
        """
        pass

    def test_list_node_js_builds_v1(self) -> None:
        """Test case for list_node_js_builds_v1

        List NodeJS builds
        """
        pass

    def test_list_node_js_environment_variables_v1(self) -> None:
        """Test case for list_node_js_environment_variables_v1

        List Node.js environment variables
        """
        pass

    def test_list_node_js_vulnerabilities_v1(self) -> None:
        """Test case for list_node_js_vulnerabilities_v1

        List Node.js vulnerabilities
        """
        pass

    def test_patch_node_js_vulnerabilities_v1(self) -> None:
        """Test case for patch_node_js_vulnerabilities_v1

        Patch Node.js vulnerabilities
        """
        pass

    def test_replace_node_js_environment_variables_v1(self) -> None:
        """Test case for replace_node_js_environment_variables_v1

        Replace Node.js environment variables
        """
        pass

    def test_restart_node_js_application_v1(self) -> None:
        """Test case for restart_node_js_application_v1

        Restart Node.js application
        """
        pass

    def test_start_node_js_build_v1(self) -> None:
        """Test case for start_node_js_build_v1

        Start Node.js build
        """
        pass

    def test_update_node_js_build_settings_v1(self) -> None:
        """Test case for update_node_js_build_settings_v1

        Update Node.js build settings
        """
        pass


if __name__ == '__main__':
    unittest.main()
