# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.20.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.hosting_v1_domains_create_subdomain_request import HostingV1DomainsCreateSubdomainRequest

class TestHostingV1DomainsCreateSubdomainRequest(unittest.TestCase):
    """HostingV1DomainsCreateSubdomainRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HostingV1DomainsCreateSubdomainRequest:
        """Test HostingV1DomainsCreateSubdomainRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HostingV1DomainsCreateSubdomainRequest`
        """
        model = HostingV1DomainsCreateSubdomainRequest()
        if include_optional:
            return HostingV1DomainsCreateSubdomainRequest(
                subdomain = 'blog',
                directory = 'blog',
                is_using_public_directory = True
            )
        else:
            return HostingV1DomainsCreateSubdomainRequest(
                subdomain = 'blog',
        )
        """

    def testHostingV1DomainsCreateSubdomainRequest(self):
        """Test HostingV1DomainsCreateSubdomainRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
