# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.11.1

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.hosting_list_websites_v1200_response import HostingListWebsitesV1200Response

class TestHostingListWebsitesV1200Response(unittest.TestCase):
    """HostingListWebsitesV1200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HostingListWebsitesV1200Response:
        """Test HostingListWebsitesV1200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HostingListWebsitesV1200Response`
        """
        model = HostingListWebsitesV1200Response()
        if include_optional:
            return HostingListWebsitesV1200Response(
                data = [
                    hostinger_api.models.hosting/v1/websites/website_resource.Hosting.V1.Websites.WebsiteResource(
                        domain = 'example.com', 
                        vhost_type = 'main', 
                        is_enabled = True, 
                        username = 'cl_user123', 
                        client_id = 67890, 
                        order_id = 12345, 
                        created_at = '2024-01-15T10:30Z', 
                        root_directory = '/home/u123456798/domains/example.com/public_html', 
                        parent_domain = 'parent.com', )
                    ],
                meta = hostinger_api.models.common/schema/pagination_meta_schema.Common.Schema.PaginationMetaSchema(
                    current_page = 1, 
                    per_page = 15, 
                    total = 100, )
            )
        else:
            return HostingListWebsitesV1200Response(
        )
        """

    def testHostingListWebsitesV1200Response(self):
        """Test HostingListWebsitesV1200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
