# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.37.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.mail_list_aliases_v1200_response import MailListAliasesV1200Response

class TestMailListAliasesV1200Response(unittest.TestCase):
    """MailListAliasesV1200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MailListAliasesV1200Response:
        """Test MailListAliasesV1200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MailListAliasesV1200Response`
        """
        model = MailListAliasesV1200Response()
        if include_optional:
            return MailListAliasesV1200Response(
                data = [
                    hostinger_api.models.mail/v1/aliases/alias_resource.Mail.V1.Aliases.AliasResource(
                        id = 'AA1a2b3c4d5e6f7g', 
                        address = 'info@example.com', 
                        mailbox = hostinger_api.models.mail/v1/aliases/alias_mailbox_resource.Mail.V1.Aliases.AliasMailboxResource(
                            id = 'AC1a2b3c4d5e6f7g', 
                            address = 'john@example.com', ), 
                        is_active = True, 
                        created_at = '2026-07-27T12:00Z', 
                        updated_at = '2026-07-27T12:00Z', )
                    ],
                meta = hostinger_api.models.common/schema/pagination_meta_schema.Common.Schema.PaginationMetaSchema(
                    current_page = 1, 
                    per_page = 15, 
                    total = 100, )
            )
        else:
            return MailListAliasesV1200Response(
        )
        """

    def testMailListAliasesV1200Response(self):
        """Test MailListAliasesV1200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
