# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.16.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.reach_v1_contacts_segments_store_request import ReachV1ContactsSegmentsStoreRequest

class TestReachV1ContactsSegmentsStoreRequest(unittest.TestCase):
    """ReachV1ContactsSegmentsStoreRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReachV1ContactsSegmentsStoreRequest:
        """Test ReachV1ContactsSegmentsStoreRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReachV1ContactsSegmentsStoreRequest`
        """
        model = ReachV1ContactsSegmentsStoreRequest()
        if include_optional:
            return ReachV1ContactsSegmentsStoreRequest(
                name = 'New segment name',
                conditions = [
                    hostinger_api.models.reach_v1_contacts_segments_store_request_conditions_inner.Reach_V1_Contacts_Segments_StoreRequest_conditions_inner(
                        operator = 'equals', 
                        value = null, 
                        attribute = 'note', )
                    ],
                logic = 'AND'
            )
        else:
            return ReachV1ContactsSegmentsStoreRequest(
                name = 'New segment name',
                conditions = [
                    hostinger_api.models.reach_v1_contacts_segments_store_request_conditions_inner.Reach_V1_Contacts_Segments_StoreRequest_conditions_inner(
                        operator = 'equals', 
                        value = null, 
                        attribute = 'note', )
                    ],
                logic = 'AND',
        )
        """

    def testReachV1ContactsSegmentsStoreRequest(self):
        """Test ReachV1ContactsSegmentsStoreRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
