# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.62.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.api.vpsssh_keys_api import VPSSSHKeysApi


class TestVPSSSHKeysApi(unittest.TestCase):
    """VPSSSHKeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VPSSSHKeysApi()

    def tearDown(self) -> None:
        pass

    def test_add_virtual_machine_ssh_keys_v1(self) -> None:
        """Test case for add_virtual_machine_ssh_keys_v1

        Add virtual machine SSH keys
        """
        pass

    def test_list_virtual_machine_ssh_keys_v1(self) -> None:
        """Test case for list_virtual_machine_ssh_keys_v1

        List virtual machine SSH keys
        """
        pass

    def test_remove_virtual_machine_ssh_keys_v1(self) -> None:
        """Test case for remove_virtual_machine_ssh_keys_v1

        Remove virtual machine SSH keys
        """
        pass


if __name__ == '__main__':
    unittest.main()
