# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.48.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.ecommerce_v1_product_product_resource_variants_inner import EcommerceV1ProductProductResourceVariantsInner

class TestEcommerceV1ProductProductResourceVariantsInner(unittest.TestCase):
    """EcommerceV1ProductProductResourceVariantsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EcommerceV1ProductProductResourceVariantsInner:
        """Test EcommerceV1ProductProductResourceVariantsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EcommerceV1ProductProductResourceVariantsInner`
        """
        model = EcommerceV1ProductProductResourceVariantsInner()
        if include_optional:
            return EcommerceV1ProductProductResourceVariantsInner(
                id = 'variant_01J8Z5F8W9K8M4A7B3C2D1E0FG',
                title = 'Medium',
                sku = 'TSHIRT-BLU-M',
                options = [
                    hostinger_api.models.ecommerce_v1_product_product_resource_variants_inner_options_inner.Ecommerce_V1_Product_ProductResource_variants_inner_options_inner(
                        name = 'Size', 
                        value = 'M', )
                    ],
                prices = [
                    hostinger_api.models.ecommerce_v1_product_product_resource_variants_inner_prices_inner.Ecommerce_V1_Product_ProductResource_variants_inner_prices_inner(
                        amount = 1999, 
                        sale_amount = 56, 
                        currency_code = 'usd', )
                    ],
                inventory_quantity = 42,
                manage_inventory = True
            )
        else:
            return EcommerceV1ProductProductResourceVariantsInner(
        )
        """

    def testEcommerceV1ProductProductResourceVariantsInner(self):
        """Test EcommerceV1ProductProductResourceVariantsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
