# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.11.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.hosting_v1_cache_toggle_cacheless_mode_request import HostingV1CacheToggleCachelessModeRequest

class TestHostingV1CacheToggleCachelessModeRequest(unittest.TestCase):
    """HostingV1CacheToggleCachelessModeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HostingV1CacheToggleCachelessModeRequest:
        """Test HostingV1CacheToggleCachelessModeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HostingV1CacheToggleCachelessModeRequest`
        """
        model = HostingV1CacheToggleCachelessModeRequest()
        if include_optional:
            return HostingV1CacheToggleCachelessModeRequest(
                enabled = True
            )
        else:
            return HostingV1CacheToggleCachelessModeRequest(
                enabled = True,
        )
        """

    def testHostingV1CacheToggleCachelessModeRequest(self):
        """Test HostingV1CacheToggleCachelessModeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
