# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.15.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.vpsv1_action_list_response import VPSV1ActionListResponse

class TestVPSV1ActionListResponse(unittest.TestCase):
    """VPSV1ActionListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VPSV1ActionListResponse:
        """Test VPSV1ActionListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VPSV1ActionListResponse`
        """
        model = VPSV1ActionListResponse()
        if include_optional:
            return VPSV1ActionListResponse(
                data = [
                    hostinger_api.models.vps/v1/action/action_resource.VPS.V1.Action.ActionResource(
                        id = 8123712, 
                        name = 'action_name', 
                        state = 'success', 
                        created_at = '2025-02-27T11:54Z', 
                        updated_at = '2025-02-27T11:58Z', )
                    ],
                meta = hostinger_api.models.common/schema/pagination_meta_schema.Common.Schema.PaginationMetaSchema(
                    current_page = 1, 
                    per_page = 15, 
                    total = 100, )
            )
        else:
            return VPSV1ActionListResponse(
        )
        """

    def testVPSV1ActionListResponse(self):
        """Test VPSV1ActionListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
