# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.8.1

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.agency_hosting_v1_websites_cron_jobs_cron_job_resource import AgencyHostingV1WebsitesCronJobsCronJobResource

class TestAgencyHostingV1WebsitesCronJobsCronJobResource(unittest.TestCase):
    """AgencyHostingV1WebsitesCronJobsCronJobResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgencyHostingV1WebsitesCronJobsCronJobResource:
        """Test AgencyHostingV1WebsitesCronJobsCronJobResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgencyHostingV1WebsitesCronJobsCronJobResource`
        """
        model = AgencyHostingV1WebsitesCronJobsCronJobResource()
        if include_optional:
            return AgencyHostingV1WebsitesCronJobsCronJobResource(
                uuid = '01931d6f-68f5-7b72-8d9e-09c6e1e6aa0e',
                time = '*/30 * * * *',
                command = 'php artisan schedule:run',
                created_at = '2024-10-28T12:00Z'
            )
        else:
            return AgencyHostingV1WebsitesCronJobsCronJobResource(
        )
        """

    def testAgencyHostingV1WebsitesCronJobsCronJobResource(self):
        """Test AgencyHostingV1WebsitesCronJobsCronJobResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
