# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.11.1

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.hosting_v1_datacenter_datacenter_resource import HostingV1DatacenterDatacenterResource

class TestHostingV1DatacenterDatacenterResource(unittest.TestCase):
    """HostingV1DatacenterDatacenterResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HostingV1DatacenterDatacenterResource:
        """Test HostingV1DatacenterDatacenterResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HostingV1DatacenterDatacenterResource`
        """
        model = HostingV1DatacenterDatacenterResource()
        if include_optional:
            return HostingV1DatacenterDatacenterResource(
                title = 'Europe (UK)',
                code = 'uk-fast',
                coordinates = hostinger_api.models.hosting/v1/datacenter/coordinates_resource.Hosting.V1.Datacenter.CoordinatesResource(
                    latitude = 51.5074, 
                    longitude = 0.1278, )
            )
        else:
            return HostingV1DatacenterDatacenterResource(
        )
        """

    def testHostingV1DatacenterDatacenterResource(self):
        """Test HostingV1DatacenterDatacenterResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
