# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.18.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.hosting_v1_orders_order_resource import HostingV1OrdersOrderResource

class TestHostingV1OrdersOrderResource(unittest.TestCase):
    """HostingV1OrdersOrderResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HostingV1OrdersOrderResource:
        """Test HostingV1OrdersOrderResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HostingV1OrdersOrderResource`
        """
        model = HostingV1OrdersOrderResource()
        if include_optional:
            return HostingV1OrdersOrderResource(
                id = 12345,
                client_id = 67890,
                subscription_id = 'sub_abc123',
                created_at = '2023-10-08T12:00Z',
                plan = hostinger_api.models.hosting/v1/orders/plan_resource.Hosting.V1.Orders.PlanResource(
                    name = 'hostinger_business', ),
                status = 'active'
            )
        else:
            return HostingV1OrdersOrderResource(
        )
        """

    def testHostingV1OrdersOrderResource(self):
        """Test HostingV1OrdersOrderResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
