# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.46.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.ecommerce_v1_discount_discount_response_resource import EcommerceV1DiscountDiscountResponseResource

class TestEcommerceV1DiscountDiscountResponseResource(unittest.TestCase):
    """EcommerceV1DiscountDiscountResponseResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EcommerceV1DiscountDiscountResponseResource:
        """Test EcommerceV1DiscountDiscountResponseResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EcommerceV1DiscountDiscountResponseResource`
        """
        model = EcommerceV1DiscountDiscountResponseResource()
        if include_optional:
            return EcommerceV1DiscountDiscountResponseResource(
                data = hostinger_api.models.ecommerce/v1/discount/discount_resource.Ecommerce.V1.Discount.DiscountResource(
                    id = 'disc_01J8Z5F8W9K8M4A7B3C2D1E0FG', 
                    code = 'BLACKFRIDAY', 
                    name = 'Black Friday', 
                    type = 'percentage', 
                    value = 20, 
                    allocation = 'total', 
                    is_disabled = False, 
                    starts_at = '2026-01-21T07:35:04Z', 
                    ends_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    usage_limit = 56, 
                    usage_count = 0, )
            )
        else:
            return EcommerceV1DiscountDiscountResponseResource(
        )
        """

    def testEcommerceV1DiscountDiscountResponseResource(self):
        """Test EcommerceV1DiscountDiscountResponseResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
