# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.46.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.ecommerce_v1_product_product_resource_variants_inner_options_inner import EcommerceV1ProductProductResourceVariantsInnerOptionsInner

class TestEcommerceV1ProductProductResourceVariantsInnerOptionsInner(unittest.TestCase):
    """EcommerceV1ProductProductResourceVariantsInnerOptionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EcommerceV1ProductProductResourceVariantsInnerOptionsInner:
        """Test EcommerceV1ProductProductResourceVariantsInnerOptionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EcommerceV1ProductProductResourceVariantsInnerOptionsInner`
        """
        model = EcommerceV1ProductProductResourceVariantsInnerOptionsInner()
        if include_optional:
            return EcommerceV1ProductProductResourceVariantsInnerOptionsInner(
                name = 'Size',
                value = 'M'
            )
        else:
            return EcommerceV1ProductProductResourceVariantsInnerOptionsInner(
        )
        """

    def testEcommerceV1ProductProductResourceVariantsInnerOptionsInner(self):
        """Test EcommerceV1ProductProductResourceVariantsInnerOptionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
