# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.45.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.ecommerce_v1_order_order_detail_resource_items_inner import EcommerceV1OrderOrderDetailResourceItemsInner

class TestEcommerceV1OrderOrderDetailResourceItemsInner(unittest.TestCase):
    """EcommerceV1OrderOrderDetailResourceItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EcommerceV1OrderOrderDetailResourceItemsInner:
        """Test EcommerceV1OrderOrderDetailResourceItemsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EcommerceV1OrderOrderDetailResourceItemsInner`
        """
        model = EcommerceV1OrderOrderDetailResourceItemsInner()
        if include_optional:
            return EcommerceV1OrderOrderDetailResourceItemsInner(
                id = 'item_01J8Z5F8W9K8M4A7B3C2D1E0FG',
                title = 'Blue T-Shirt / M',
                sku = 'TSHIRT-BLU-M',
                variant_id = 'variant_01J8Z5F8W9K8M4A7B3C2D1E0FG',
                quantity = 2,
                fulfilled_quantity = 0,
                returned_quantity = 0,
                unit_price = 2250,
                total = 4500
            )
        else:
            return EcommerceV1OrderOrderDetailResourceItemsInner(
        )
        """

    def testEcommerceV1OrderOrderDetailResourceItemsInner(self):
        """Test EcommerceV1OrderOrderDetailResourceItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
