# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.32.3

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.api.hosting_files_api import HostingFilesApi


class TestHostingFilesApi(unittest.TestCase):
    """HostingFilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HostingFilesApi()

    def tearDown(self) -> None:
        pass

    def test_get_website_file_content_v1(self) -> None:
        """Test case for get_website_file_content_v1

        Get website file content
        """
        pass

    def test_list_website_files_and_directories_v1(self) -> None:
        """Test case for list_website_files_and_directories_v1

        List website files and directories
        """
        pass


if __name__ == '__main__':
    unittest.main()
