# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.8.1

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.word_press_v1_plugins_available_plugin_resource import WordPressV1PluginsAvailablePluginResource

class TestWordPressV1PluginsAvailablePluginResource(unittest.TestCase):
    """WordPressV1PluginsAvailablePluginResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WordPressV1PluginsAvailablePluginResource:
        """Test WordPressV1PluginsAvailablePluginResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WordPressV1PluginsAvailablePluginResource`
        """
        model = WordPressV1PluginsAvailablePluginResource()
        if include_optional:
            return WordPressV1PluginsAvailablePluginResource(
                slug = 'akismet',
                title = 'Akismet Anti-Spam',
                description = 'Protect your site from spam.',
                onboarding_description_slug = 'akismet_onboarding_description',
                recommended_description_slug = 'akismet_recommended_description',
                link = 'https://wordpress.org/plugins/akismet/',
                version = '5.3',
                required_wordpress_version = '5.8',
                required_php_version = '7.2',
                is_plan_upgrade_needed = False
            )
        else:
            return WordPressV1PluginsAvailablePluginResource(
        )
        """

    def testWordPressV1PluginsAvailablePluginResource(self):
        """Test WordPressV1PluginsAvailablePluginResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
