# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.35.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.reach_v1_forms_form_details_resource import ReachV1FormsFormDetailsResource

class TestReachV1FormsFormDetailsResource(unittest.TestCase):
    """ReachV1FormsFormDetailsResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReachV1FormsFormDetailsResource:
        """Test ReachV1FormsFormDetailsResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReachV1FormsFormDetailsResource`
        """
        model = ReachV1FormsFormDetailsResource()
        if include_optional:
            return ReachV1FormsFormDetailsResource(
                uuid = '550e8400-e29b-41d4-a716-446655440000',
                name = 'Newsletter signup',
                status = 'active',
                type = 'form',
                template = hostinger_api.models.reach/v1/forms/form_template_details_resource.Reach.V1.Forms.FormTemplateDetailsResource(
                    uuid = '2080cc86-e026-4f7b-9598-d4132f8c7c2f', 
                    path = 'forms/8f2c1b9e-1f4a-4a1e-9a2b-2f3c4d5e6f70/9a1b2c3d.html', 
                    url = 'https://cdn-reach.hostinger.com/storage/client123/profile-uuid/form.html', ),
                tags = [
                    hostinger_api.models.reach/v1/forms/form_tag_resource.Reach.V1.Forms.FormTagResource(
                        uuid = '550e8400-e29b-41d4-a716-446655440000', 
                        value = 'Newsletter', 
                        type = 'system', )
                    ],
                created_at = '2025-02-27T11:54:22Z',
                updated_at = '2025-03-04T09:12:07Z'
            )
        else:
            return ReachV1FormsFormDetailsResource(
        )
        """

    def testReachV1FormsFormDetailsResource(self):
        """Test ReachV1FormsFormDetailsResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
