# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.14.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.vpsv1_post_install_script_list_response import VPSV1PostInstallScriptListResponse

class TestVPSV1PostInstallScriptListResponse(unittest.TestCase):
    """VPSV1PostInstallScriptListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VPSV1PostInstallScriptListResponse:
        """Test VPSV1PostInstallScriptListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VPSV1PostInstallScriptListResponse`
        """
        model = VPSV1PostInstallScriptListResponse()
        if include_optional:
            return VPSV1PostInstallScriptListResponse(
                data = [
                    hostinger_api.models.vps/v1/post_install_script/post_install_script_resource.VPS.V1.PostInstallScript.PostInstallScriptResource(
                        id = 325, 
                        name = 'My Setup Script', 
                        content = '#!/bin/bash\napt-get update\napt-get install -y nginx', 
                        created_at = '2025-02-27T11:54:22Z', 
                        updated_at = '2025-03-19T11:54:22Z', )
                    ],
                meta = hostinger_api.models.common/schema/pagination_meta_schema.Common.Schema.PaginationMetaSchema(
                    current_page = 1, 
                    per_page = 15, 
                    total = 100, )
            )
        else:
            return VPSV1PostInstallScriptListResponse(
        )
        """

    def testVPSV1PostInstallScriptListResponse(self):
        """Test VPSV1PostInstallScriptListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
