# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.49.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.agency_hosting_v1_orders_disk_usage_metrics_metric_resource import AgencyHostingV1OrdersDiskUsageMetricsMetricResource

class TestAgencyHostingV1OrdersDiskUsageMetricsMetricResource(unittest.TestCase):
    """AgencyHostingV1OrdersDiskUsageMetricsMetricResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgencyHostingV1OrdersDiskUsageMetricsMetricResource:
        """Test AgencyHostingV1OrdersDiskUsageMetricsMetricResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgencyHostingV1OrdersDiskUsageMetricsMetricResource`
        """
        model = AgencyHostingV1OrdersDiskUsageMetricsMetricResource()
        if include_optional:
            return AgencyHostingV1OrdersDiskUsageMetricsMetricResource(
                disk_bytes = 104857600,
                inodes = 400000,
                timestamp = 1736325738
            )
        else:
            return AgencyHostingV1OrdersDiskUsageMetricsMetricResource(
        )
        """

    def testAgencyHostingV1OrdersDiskUsageMetricsMetricResource(self):
        """Test AgencyHostingV1OrdersDiskUsageMetricsMetricResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
