# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.54.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.horizons_v1_websites_edit_website_request import HorizonsV1WebsitesEditWebsiteRequest

class TestHorizonsV1WebsitesEditWebsiteRequest(unittest.TestCase):
    """HorizonsV1WebsitesEditWebsiteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HorizonsV1WebsitesEditWebsiteRequest:
        """Test HorizonsV1WebsitesEditWebsiteRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HorizonsV1WebsitesEditWebsiteRequest`
        """
        model = HorizonsV1WebsitesEditWebsiteRequest()
        if include_optional:
            return HorizonsV1WebsitesEditWebsiteRequest(
                message = [
                    hostinger_api.models.horizons_v1_websites_edit_website_request_message_inner.Horizons_V1_Websites_EditWebsiteRequest_message_inner(
                        type = 'text', 
                        text = 'Add a testimonials section below the menu and make the hero background green', )
                    ]
            )
        else:
            return HorizonsV1WebsitesEditWebsiteRequest(
                message = [
                    hostinger_api.models.horizons_v1_websites_edit_website_request_message_inner.Horizons_V1_Websites_EditWebsiteRequest_message_inner(
                        type = 'text', 
                        text = 'Add a testimonials section below the menu and make the hero background green', )
                    ],
        )
        """

    def testHorizonsV1WebsitesEditWebsiteRequest(self):
        """Test HorizonsV1WebsitesEditWebsiteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
