# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.19.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.mail_v1_schema_update_webhook_request_schema import MailV1SchemaUpdateWebhookRequestSchema

class TestMailV1SchemaUpdateWebhookRequestSchema(unittest.TestCase):
    """MailV1SchemaUpdateWebhookRequestSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MailV1SchemaUpdateWebhookRequestSchema:
        """Test MailV1SchemaUpdateWebhookRequestSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MailV1SchemaUpdateWebhookRequestSchema`
        """
        model = MailV1SchemaUpdateWebhookRequestSchema()
        if include_optional:
            return MailV1SchemaUpdateWebhookRequestSchema(
                name = 'Updated notifier',
                description = 'Now also handles newsletters',
                events = [
                    'message.received'
                    ],
                status = 'paused',
                url = 'https://example.com/webhooks/incoming'
            )
        else:
            return MailV1SchemaUpdateWebhookRequestSchema(
        )
        """

    def testMailV1SchemaUpdateWebhookRequestSchema(self):
        """Test MailV1SchemaUpdateWebhookRequestSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
