# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.54.1

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.hosting_v1_git_git_repository_resource import HostingV1GitGitRepositoryResource

class TestHostingV1GitGitRepositoryResource(unittest.TestCase):
    """HostingV1GitGitRepositoryResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HostingV1GitGitRepositoryResource:
        """Test HostingV1GitGitRepositoryResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HostingV1GitGitRepositoryResource`
        """
        model = HostingV1GitGitRepositoryResource()
        if include_optional:
            return HostingV1GitGitRepositoryResource(
                id = 12345,
                name = 'my-repository',
                full_name = 'octocat/my-repository',
                owner = 'octocat',
                is_private = False,
                html_url = 'https://github.com/octocat/my-repository',
                clone_url = 'https://github.com/octocat/my-repository.git',
                default_branch = 'main'
            )
        else:
            return HostingV1GitGitRepositoryResource(
                id = 12345,
                name = 'my-repository',
                full_name = 'octocat/my-repository',
                owner = 'octocat',
                is_private = False,
                html_url = 'https://github.com/octocat/my-repository',
                clone_url = 'https://github.com/octocat/my-repository.git',
                default_branch = 'main',
        )
        """

    def testHostingV1GitGitRepositoryResource(self):
        """Test HostingV1GitGitRepositoryResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
