# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.54.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.hosting_v1_databases_website_database_resource import HostingV1DatabasesWebsiteDatabaseResource

class TestHostingV1DatabasesWebsiteDatabaseResource(unittest.TestCase):
    """HostingV1DatabasesWebsiteDatabaseResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HostingV1DatabasesWebsiteDatabaseResource:
        """Test HostingV1DatabasesWebsiteDatabaseResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HostingV1DatabasesWebsiteDatabaseResource`
        """
        model = HostingV1DatabasesWebsiteDatabaseResource()
        if include_optional:
            return HostingV1DatabasesWebsiteDatabaseResource(
                database = hostinger_api.models.hosting/v1/databases/website_database_connection_resource.Hosting.V1.Databases.WebsiteDatabaseConnectionResource(
                    name = 'u123456789_aB3dE', 
                    user = 'u123456789_xY9zW', 
                    host = 'localhost', 
                    port = 3306, ),
                env_var_keys = ["DB_HOST","DB_PORT","DB_NAME","DB_USER","DB_PASSWORD","DATABASE_URL"]
            )
        else:
            return HostingV1DatabasesWebsiteDatabaseResource(
                database = hostinger_api.models.hosting/v1/databases/website_database_connection_resource.Hosting.V1.Databases.WebsiteDatabaseConnectionResource(
                    name = 'u123456789_aB3dE', 
                    user = 'u123456789_xY9zW', 
                    host = 'localhost', 
                    port = 3306, ),
                env_var_keys = ["DB_HOST","DB_PORT","DB_NAME","DB_USER","DB_PASSWORD","DATABASE_URL"],
        )
        """

    def testHostingV1DatabasesWebsiteDatabaseResource(self):
        """Test HostingV1DatabasesWebsiteDatabaseResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
