# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.12.1

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.hosting_v1_domains_free_subdomain_resource import HostingV1DomainsFreeSubdomainResource

class TestHostingV1DomainsFreeSubdomainResource(unittest.TestCase):
    """HostingV1DomainsFreeSubdomainResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HostingV1DomainsFreeSubdomainResource:
        """Test HostingV1DomainsFreeSubdomainResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HostingV1DomainsFreeSubdomainResource`
        """
        model = HostingV1DomainsFreeSubdomainResource()
        if include_optional:
            return HostingV1DomainsFreeSubdomainResource(
                domain = 'palegreen-fox-548498.hostingersite.com'
            )
        else:
            return HostingV1DomainsFreeSubdomainResource(
        )
        """

    def testHostingV1DomainsFreeSubdomainResource(self):
        """Test HostingV1DomainsFreeSubdomainResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
