# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.44.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.hosting_v1_node_js_build_settings_resource import HostingV1NodeJsBuildSettingsResource

class TestHostingV1NodeJsBuildSettingsResource(unittest.TestCase):
    """HostingV1NodeJsBuildSettingsResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HostingV1NodeJsBuildSettingsResource:
        """Test HostingV1NodeJsBuildSettingsResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HostingV1NodeJsBuildSettingsResource`
        """
        model = HostingV1NodeJsBuildSettingsResource()
        if include_optional:
            return HostingV1NodeJsBuildSettingsResource(
                app_type = 'create-react-app',
                node_version = 18,
                root_directory = 'frontend',
                output_directory = 'dist',
                build_script = 'build',
                entry_file = 'server.js',
                package_manager = 'npm',
                available_scripts = ["build","test"]
            )
        else:
            return HostingV1NodeJsBuildSettingsResource(
                app_type = 'create-react-app',
                node_version = 18,
                root_directory = 'frontend',
                output_directory = 'dist',
                build_script = 'build',
                entry_file = 'server.js',
                package_manager = 'npm',
                available_scripts = ["build","test"],
        )
        """

    def testHostingV1NodeJsBuildSettingsResource(self):
        """Test HostingV1NodeJsBuildSettingsResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
