# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.19.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.api.ecommerce_miscellaneous_api import EcommerceMiscellaneousApi


class TestEcommerceMiscellaneousApi(unittest.TestCase):
    """EcommerceMiscellaneousApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EcommerceMiscellaneousApi()

    def tearDown(self) -> None:
        pass

    def test_get_custom_storefront_setup_instructions_v1(self) -> None:
        """Test case for get_custom_storefront_setup_instructions_v1

        Get custom storefront setup instructions
        """
        pass


if __name__ == '__main__':
    unittest.main()
