# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.12.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.agency_hosting_list_agency_plan_domains_v1200_response import AgencyHostingListAgencyPlanDomainsV1200Response

class TestAgencyHostingListAgencyPlanDomainsV1200Response(unittest.TestCase):
    """AgencyHostingListAgencyPlanDomainsV1200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgencyHostingListAgencyPlanDomainsV1200Response:
        """Test AgencyHostingListAgencyPlanDomainsV1200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgencyHostingListAgencyPlanDomainsV1200Response`
        """
        model = AgencyHostingListAgencyPlanDomainsV1200Response()
        if include_optional:
            return AgencyHostingListAgencyPlanDomainsV1200Response(
                data = [
                    hostinger_api.models.agency_hosting/v1/domains/domain_resource.AgencyHosting.V1.Domains.DomainResource(
                        fqdn = 'example.com', 
                        website_uid = 'zpwlGlp19', 
                        created_at = '2024-05-29T05:49:49Z', )
                    ],
                meta = hostinger_api.models.common/schema/pagination_meta_schema.Common.Schema.PaginationMetaSchema(
                    current_page = 1, 
                    per_page = 15, 
                    total = 100, )
            )
        else:
            return AgencyHostingListAgencyPlanDomainsV1200Response(
        )
        """

    def testAgencyHostingListAgencyPlanDomainsV1200Response(self):
        """Test AgencyHostingListAgencyPlanDomainsV1200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
