# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.19.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.api.agency_hosting_orders_api import AgencyHostingOrdersApi


class TestAgencyHostingOrdersApi(unittest.TestCase):
    """AgencyHostingOrdersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgencyHostingOrdersApi()

    def tearDown(self) -> None:
        pass

    def test_list_agency_plan_orders_v1(self) -> None:
        """Test case for list_agency_plan_orders_v1

        List Agency Plan orders
        """
        pass


if __name__ == '__main__':
    unittest.main()
