# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.6.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.ecommerce_v1_sales_channel_sales_channel_creation_resource_sales_channel import EcommerceV1SalesChannelSalesChannelCreationResourceSalesChannel

class TestEcommerceV1SalesChannelSalesChannelCreationResourceSalesChannel(unittest.TestCase):
    """EcommerceV1SalesChannelSalesChannelCreationResourceSalesChannel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EcommerceV1SalesChannelSalesChannelCreationResourceSalesChannel:
        """Test EcommerceV1SalesChannelSalesChannelCreationResourceSalesChannel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EcommerceV1SalesChannelSalesChannelCreationResourceSalesChannel`
        """
        model = EcommerceV1SalesChannelSalesChannelCreationResourceSalesChannel()
        if include_optional:
            return EcommerceV1SalesChannelSalesChannelCreationResourceSalesChannel(
                id = 'scha_01J8Z5F8W9K8M4A7B3C2D1E0FG',
                type = 'custom',
                is_primary = False,
                is_active = True,
                external_id = '',
                name = 'Vintagio Onepager',
                domain = 'https://www.bestshirt.vintagio.com'
            )
        else:
            return EcommerceV1SalesChannelSalesChannelCreationResourceSalesChannel(
        )
        """

    def testEcommerceV1SalesChannelSalesChannelCreationResourceSalesChannel(self):
        """Test EcommerceV1SalesChannelSalesChannelCreationResourceSalesChannel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
