# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.46.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.ecommerce_v1_payment_provider_payment_provider_list_resource_data import EcommerceV1PaymentProviderPaymentProviderListResourceData

class TestEcommerceV1PaymentProviderPaymentProviderListResourceData(unittest.TestCase):
    """EcommerceV1PaymentProviderPaymentProviderListResourceData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EcommerceV1PaymentProviderPaymentProviderListResourceData:
        """Test EcommerceV1PaymentProviderPaymentProviderListResourceData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EcommerceV1PaymentProviderPaymentProviderListResourceData`
        """
        model = EcommerceV1PaymentProviderPaymentProviderListResourceData()
        if include_optional:
            return EcommerceV1PaymentProviderPaymentProviderListResourceData(
                connected = [
                    hostinger_api.models.ecommerce_v1_payment_provider_payment_provider_list_resource_data_connected_inner.Ecommerce_V1_PaymentProvider_PaymentProviderListResource_data_connected_inner(
                        id = 'storepp_01J8Z5F8W9K8M4A7B3C2D1E0FG', 
                        provider_id = 'stripe', 
                        title = 'Stripe', 
                        is_enabled = True, 
                        status = 'connected', 
                        shows_at_checkout = True, )
                    ],
                available = [
                    hostinger_api.models.ecommerce_v1_payment_provider_payment_provider_list_resource_data_available_inner.Ecommerce_V1_PaymentProvider_PaymentProviderListResource_data_available_inner(
                        id = 'stripe', 
                        is_installed = False, 
                        is_enabled = False, 
                        is_currency_supported = True, 
                        supported_currencies = [
                            'usd'
                            ], )
                    ]
            )
        else:
            return EcommerceV1PaymentProviderPaymentProviderListResourceData(
        )
        """

    def testEcommerceV1PaymentProviderPaymentProviderListResourceData(self):
        """Test EcommerceV1PaymentProviderPaymentProviderListResourceData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
