# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.20.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.api.mail_forwarders_api import MailForwardersApi


class TestMailForwardersApi(unittest.TestCase):
    """MailForwardersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MailForwardersApi()

    def tearDown(self) -> None:
        pass

    def test_create_forwarder_v1(self) -> None:
        """Test case for create_forwarder_v1

        Create forwarder
        """
        pass

    def test_delete_forwarder_v1(self) -> None:
        """Test case for delete_forwarder_v1

        Delete forwarder
        """
        pass

    def test_list_forwarders_v1(self) -> None:
        """Test case for list_forwarders_v1

        List forwarders
        """
        pass

    def test_resend_forwarder_confirmation_v1(self) -> None:
        """Test case for resend_forwarder_confirmation_v1

        Resend forwarder confirmation
        """
        pass

    def test_update_forwarder_keep_copy_setting_v1(self) -> None:
        """Test case for update_forwarder_keep_copy_setting_v1

        Update forwarder keep-copy setting
        """
        pass


if __name__ == '__main__':
    unittest.main()
