# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.42.3

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.mail_v1_catchalls_catchall_resource import MailV1CatchallsCatchallResource

class TestMailV1CatchallsCatchallResource(unittest.TestCase):
    """MailV1CatchallsCatchallResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MailV1CatchallsCatchallResource:
        """Test MailV1CatchallsCatchallResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MailV1CatchallsCatchallResource`
        """
        model = MailV1CatchallsCatchallResource()
        if include_optional:
            return MailV1CatchallsCatchallResource(
                id = 'CA1a2b3c4d5e6f7g',
                mailbox = hostinger_api.models.mail/v1/catchalls/catchall_mailbox_resource.Mail.V1.Catchalls.CatchallMailboxResource(
                    id = 'AC1a2b3c4d5e6f7g', 
                    address = 'user@example.com', ),
                domain = 'example.com',
                is_active = True,
                is_confirmed = True,
                created_at = '2026-07-27T12:00Z',
                updated_at = '2026-07-27T12:00Z'
            )
        else:
            return MailV1CatchallsCatchallResource(
        )
        """

    def testMailV1CatchallsCatchallResource(self):
        """Test MailV1CatchallsCatchallResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
