# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.43.1

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.agency_hosting_v1_php_extension_resource import AgencyHostingV1PhpExtensionResource

class TestAgencyHostingV1PhpExtensionResource(unittest.TestCase):
    """AgencyHostingV1PhpExtensionResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgencyHostingV1PhpExtensionResource:
        """Test AgencyHostingV1PhpExtensionResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgencyHostingV1PhpExtensionResource`
        """
        model = AgencyHostingV1PhpExtensionResource()
        if include_optional:
            return AgencyHostingV1PhpExtensionResource(
                name = 'zip',
                description = 'Lets PHP read and write compressed ZIP archives.',
                state = 'enabled'
            )
        else:
            return AgencyHostingV1PhpExtensionResource(
        )
        """

    def testAgencyHostingV1PhpExtensionResource(self):
        """Test AgencyHostingV1PhpExtensionResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
