# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.48.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.reach_list_profile_contacts_v1200_response import ReachListProfileContactsV1200Response

class TestReachListProfileContactsV1200Response(unittest.TestCase):
    """ReachListProfileContactsV1200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReachListProfileContactsV1200Response:
        """Test ReachListProfileContactsV1200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReachListProfileContactsV1200Response`
        """
        model = ReachListProfileContactsV1200Response()
        if include_optional:
            return ReachListProfileContactsV1200Response(
                data = [
                    hostinger_api.models.reach/v1/contacts/profile_contact_resource.Reach.V1.Contacts.ProfileContactResource(
                        uuid = '550e8400-e29b-41d4-a716-446655440000', 
                        name = 'John', 
                        surname = 'Doe', 
                        email = 'john.doe@example.com', 
                        phone = '+14155552671', 
                        subscription_status = 'subscribed', 
                        subscribed_at = '2023-01-01T00:00Z', 
                        unsubscribed_at = '2023-06-15T00:00Z', 
                        source = 'api', 
                        note = 'VIP customer', )
                    ],
                meta = hostinger_api.models.common/schema/pagination_meta_schema.Common.Schema.PaginationMetaSchema(
                    current_page = 1, 
                    per_page = 15, 
                    total = 100, )
            )
        else:
            return ReachListProfileContactsV1200Response(
        )
        """

    def testReachListProfileContactsV1200Response(self):
        """Test ReachListProfileContactsV1200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
