# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.16.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.api.ecommerce_stores_api import EcommerceStoresApi


class TestEcommerceStoresApi(unittest.TestCase):
    """EcommerceStoresApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EcommerceStoresApi()

    def tearDown(self) -> None:
        pass

    def test_create_store_v1(self) -> None:
        """Test case for create_store_v1

        Create store
        """
        pass

    def test_delete_store_v1(self) -> None:
        """Test case for delete_store_v1

        Delete store
        """
        pass

    def test_get_store_metadata_v1(self) -> None:
        """Test case for get_store_metadata_v1

        Get store metadata
        """
        pass

    def test_get_stores_v1(self) -> None:
        """Test case for get_stores_v1

        Get stores
        """
        pass


if __name__ == '__main__':
    unittest.main()
