# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.11.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.word_press_v1_plugins_installed_plugin_resource import WordPressV1PluginsInstalledPluginResource

class TestWordPressV1PluginsInstalledPluginResource(unittest.TestCase):
    """WordPressV1PluginsInstalledPluginResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WordPressV1PluginsInstalledPluginResource:
        """Test WordPressV1PluginsInstalledPluginResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WordPressV1PluginsInstalledPluginResource`
        """
        model = WordPressV1PluginsInstalledPluginResource()
        if include_optional:
            return WordPressV1PluginsInstalledPluginResource(
                name = 'akismet',
                title = 'Akismet Anti-Spam',
                version = '5.3',
                status = 'active',
                update = 'none',
                vulnerabilities = [
                    hostinger_api.models.word_press/v1/common/vulnerability_resource.WordPress.V1.Common.VulnerabilityResource(
                        title = 'Cross-Site Scripting (XSS)', 
                        description = 'A stored XSS vulnerability affecting older versions.', 
                        affected_in = '4.7.0', 
                        fixed_in = '4.7.1', 
                        direct_url = 'https://www.wordfence.com/threat-intel/vulnerabilities/id/example', )
                    ]
            )
        else:
            return WordPressV1PluginsInstalledPluginResource(
        )
        """

    def testWordPressV1PluginsInstalledPluginResource(self):
        """Test WordPressV1PluginsInstalledPluginResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
