# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.46.3

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.ecommerce_list_products_v1200_response import EcommerceListProductsV1200Response

class TestEcommerceListProductsV1200Response(unittest.TestCase):
    """EcommerceListProductsV1200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EcommerceListProductsV1200Response:
        """Test EcommerceListProductsV1200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EcommerceListProductsV1200Response`
        """
        model = EcommerceListProductsV1200Response()
        if include_optional:
            return EcommerceListProductsV1200Response(
                data = [
                    hostinger_api.models.ecommerce/v1/product/product_resource.Ecommerce.V1.Product.ProductResource(
                        id = 'prod_01J8Z5F8W9K8M4A7B3C2D1E0FG', 
                        title = 'Blue T-Shirt', 
                        status = 'published', 
                        thumbnail = 'https://cdn.example.com/prod/thumb.jpg', 
                        type = 'physical', 
                        variant_count = 3, 
                        price_range = hostinger_api.models.ecommerce_v1_product_product_resource_price_range.Ecommerce_V1_Product_ProductResource_price_range(
                            min = 1999, 
                            max = 2499, 
                            currency_code = 'usd', ), 
                        variants = [
                            hostinger_api.models.ecommerce_v1_product_product_resource_variants_inner.Ecommerce_V1_Product_ProductResource_variants_inner(
                                id = 'variant_01J8Z5F8W9K8M4A7B3C2D1E0FG', 
                                title = 'Medium', 
                                sku = 'TSHIRT-BLU-M', 
                                options = [
                                    hostinger_api.models.ecommerce_v1_product_product_resource_variants_inner_options_inner.Ecommerce_V1_Product_ProductResource_variants_inner_options_inner(
                                        name = 'Size', 
                                        value = 'M', )
                                    ], 
                                prices = [
                                    hostinger_api.models.ecommerce_v1_product_product_resource_variants_inner_prices_inner.Ecommerce_V1_Product_ProductResource_variants_inner_prices_inner(
                                        amount = 1999, 
                                        sale_amount = 56, 
                                        currency_code = 'usd', )
                                    ], 
                                inventory_quantity = 42, 
                                manage_inventory = True, )
                            ], 
                        media = [
                            hostinger_api.models.ecommerce_v1_product_product_resource_media_inner.Ecommerce_V1_Product_ProductResource_media_inner(
                                url = 'https://cdn.example.com/prod/1.jpg', 
                                type = 'image', 
                                is_thumbnail = True, )
                            ], )
                    ],
                meta = hostinger_api.models.common/schema/pagination_meta_schema.Common.Schema.PaginationMetaSchema(
                    current_page = 1, 
                    per_page = 15, 
                    total = 100, )
            )
        else:
            return EcommerceListProductsV1200Response(
        )
        """

    def testEcommerceListProductsV1200Response(self):
        """Test EcommerceListProductsV1200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
