# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.42.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.domains_v1_transfer_claim_request import DomainsV1TransferClaimRequest

class TestDomainsV1TransferClaimRequest(unittest.TestCase):
    """DomainsV1TransferClaimRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DomainsV1TransferClaimRequest:
        """Test DomainsV1TransferClaimRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DomainsV1TransferClaimRequest`
        """
        model = DomainsV1TransferClaimRequest()
        if include_optional:
            return DomainsV1TransferClaimRequest(
                domain = 'my-new-domain.tld',
                auth_code = 'Auth123Code456',
                domain_contacts = hostinger_api.models.domains_v1_portfolio_claim_request_domain_contacts.Domains_V1_Portfolio_ClaimRequest_domain_contacts(
                    owner_id = 741288, 
                    admin_id = 546123, 
                    billing_id = 741288, 
                    tech_id = 741288, ),
                should_keep_ns = True
            )
        else:
            return DomainsV1TransferClaimRequest(
                domain = 'my-new-domain.tld',
                auth_code = 'Auth123Code456',
        )
        """

    def testDomainsV1TransferClaimRequest(self):
        """Test DomainsV1TransferClaimRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
