# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.7.1

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.agency_hosting_v1_websites_website_remote_access_resource import AgencyHostingV1WebsitesWebsiteRemoteAccessResource

class TestAgencyHostingV1WebsitesWebsiteRemoteAccessResource(unittest.TestCase):
    """AgencyHostingV1WebsitesWebsiteRemoteAccessResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgencyHostingV1WebsitesWebsiteRemoteAccessResource:
        """Test AgencyHostingV1WebsitesWebsiteRemoteAccessResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgencyHostingV1WebsitesWebsiteRemoteAccessResource`
        """
        model = AgencyHostingV1WebsitesWebsiteRemoteAccessResource()
        if include_optional:
            return AgencyHostingV1WebsitesWebsiteRemoteAccessResource(
                mode = 'ssh_and_sftp',
                ssh = hostinger_api.models.agency_hosting/v1/websites/website_ssh_details_resource.AgencyHosting.V1.Websites.WebsiteSshDetailsResource(
                    username = 'u123456789_abcDeFg', 
                    host = '192.161.10.1', 
                    port = 65002, 
                    is_enabled = True, 
                    is_password_enabled = True, ),
                sftp = hostinger_api.models.agency_hosting/v1/websites/website_sftp_details_resource.AgencyHosting.V1.Websites.WebsiteSftpDetailsResource(
                    username = 'u123456789_abcDeFg', 
                    host = '192.161.10.1', 
                    port = 65002, 
                    is_enabled = True, )
            )
        else:
            return AgencyHostingV1WebsitesWebsiteRemoteAccessResource(
        )
        """

    def testAgencyHostingV1WebsitesWebsiteRemoteAccessResource(self):
        """Test AgencyHostingV1WebsitesWebsiteRemoteAccessResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
