# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.45.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.reach_v1_contacts_segments_profile_store_request_conditions_inner import ReachV1ContactsSegmentsProfileStoreRequestConditionsInner

class TestReachV1ContactsSegmentsProfileStoreRequestConditionsInner(unittest.TestCase):
    """ReachV1ContactsSegmentsProfileStoreRequestConditionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReachV1ContactsSegmentsProfileStoreRequestConditionsInner:
        """Test ReachV1ContactsSegmentsProfileStoreRequestConditionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReachV1ContactsSegmentsProfileStoreRequestConditionsInner`
        """
        model = ReachV1ContactsSegmentsProfileStoreRequestConditionsInner()
        if include_optional:
            return ReachV1ContactsSegmentsProfileStoreRequestConditionsInner(
                attribute = 'email',
                operator = 'equals',
                value = 'example@example.com'
            )
        else:
            return ReachV1ContactsSegmentsProfileStoreRequestConditionsInner(
                attribute = 'email',
                operator = 'equals',
                value = 'example@example.com',
        )
        """

    def testReachV1ContactsSegmentsProfileStoreRequestConditionsInner(self):
        """Test ReachV1ContactsSegmentsProfileStoreRequestConditionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
