# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.34.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.api.agency_hosting_cron_jobs_api import AgencyHostingCronJobsApi


class TestAgencyHostingCronJobsApi(unittest.TestCase):
    """AgencyHostingCronJobsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgencyHostingCronJobsApi()

    def tearDown(self) -> None:
        pass

    def test_create_website_cron_job_v1(self) -> None:
        """Test case for create_website_cron_job_v1

        Create website cron job
        """
        pass

    def test_delete_website_cron_job_v1(self) -> None:
        """Test case for delete_website_cron_job_v1

        Delete website cron job
        """
        pass

    def test_list_website_cron_jobs_v1(self) -> None:
        """Test case for list_website_cron_jobs_v1

        List website cron jobs
        """
        pass


if __name__ == '__main__':
    unittest.main()
