# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.12.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.mail_v1_mailboxes_mailbox_protocols_resource import MailV1MailboxesMailboxProtocolsResource

class TestMailV1MailboxesMailboxProtocolsResource(unittest.TestCase):
    """MailV1MailboxesMailboxProtocolsResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MailV1MailboxesMailboxProtocolsResource:
        """Test MailV1MailboxesMailboxProtocolsResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MailV1MailboxesMailboxProtocolsResource`
        """
        model = MailV1MailboxesMailboxProtocolsResource()
        if include_optional:
            return MailV1MailboxesMailboxProtocolsResource(
                is_imap_enabled = True,
                is_pop3_enabled = True,
                is_smtp_in_enabled = True,
                is_smtp_out_enabled = True
            )
        else:
            return MailV1MailboxesMailboxProtocolsResource(
        )
        """

    def testMailV1MailboxesMailboxProtocolsResource(self):
        """Test MailV1MailboxesMailboxProtocolsResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
