# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 0.19.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_api.models.ecommerce_v1_product_create_physical_product_request import EcommerceV1ProductCreatePhysicalProductRequest

class TestEcommerceV1ProductCreatePhysicalProductRequest(unittest.TestCase):
    """EcommerceV1ProductCreatePhysicalProductRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EcommerceV1ProductCreatePhysicalProductRequest:
        """Test EcommerceV1ProductCreatePhysicalProductRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EcommerceV1ProductCreatePhysicalProductRequest`
        """
        model = EcommerceV1ProductCreatePhysicalProductRequest()
        if include_optional:
            return EcommerceV1ProductCreatePhysicalProductRequest(
                name = 'My Product',
                price = 1000,
                description = 'A great product.',
                currency = 'usd'
            )
        else:
            return EcommerceV1ProductCreatePhysicalProductRequest(
                name = 'My Product',
                price = 1000,
        )
        """

    def testEcommerceV1ProductCreatePhysicalProductRequest(self):
        """Test EcommerceV1ProductCreatePhysicalProductRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
