# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.38.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AgencyHostingV1PhpOptionResource(BaseModel):
    """
    AgencyHostingV1PhpOptionResource
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="php.ini directive name.")
    description: Optional[StrictStr] = Field(default=None, description="What the directive controls.")
    default_value: Optional[StrictStr] = Field(default=None, description="Value applied when no custom value is set.")
    allowed_values: Optional[List[StrictStr]] = Field(default=None, description="Values this option accepts. Null when the option accepts any value of its type.")
    value: Optional[StrictStr] = Field(default=None, description="Value currently in effect for the website.")
    type: Optional[StrictStr] = Field(default=None, description="Whether the option takes a single value or a list of values.")
    __properties: ClassVar[List[str]] = ["name", "description", "default_value", "allowed_values", "value", "type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['value', 'list']):
            raise ValueError("must be one of enum values ('value', 'list')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgencyHostingV1PhpOptionResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if allowed_values (nullable) is None
        # and model_fields_set contains the field
        if self.allowed_values is None and "allowed_values" in self.model_fields_set:
            _dict['allowed_values'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgencyHostingV1PhpOptionResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "default_value": obj.get("default_value"),
            "allowed_values": obj.get("allowed_values"),
            "value": obj.get("value"),
            "type": obj.get("type")
        })
        return _obj


