# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.12.1

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class AgencyHostingV1WebsitesDatabasesUsersCreateDatabaseUserRequest(BaseModel):
    """
    AgencyHostingV1WebsitesDatabasesUsersCreateDatabaseUserRequest
    """ # noqa: E501
    database_user: Annotated[str, Field(min_length=3, strict=True, max_length=12)] = Field(description="Database username to create (alphanumeric and underscores).")
    password: Annotated[str, Field(min_length=8, strict=True, max_length=50)] = Field(description="Password for the database user (requires mixed case, letters, and numbers).")
    host: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=40)]] = Field(default=None, description="Host the user connects from (IPv4, IPv6, % wildcard, or localhost). Defaults to localhost.")
    __properties: ClassVar[List[str]] = ["database_user", "password", "host"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgencyHostingV1WebsitesDatabasesUsersCreateDatabaseUserRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if host (nullable) is None
        # and model_fields_set contains the field
        if self.host is None and "host" in self.model_fields_set:
            _dict['host'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgencyHostingV1WebsitesDatabasesUsersCreateDatabaseUserRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "database_user": obj.get("database_user"),
            "password": obj.get("password"),
            "host": obj.get("host")
        })
        return _obj


