# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.44.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from hostinger_api.models.ecommerce_v1_product_product_resource_media_inner import EcommerceV1ProductProductResourceMediaInner
from hostinger_api.models.ecommerce_v1_product_product_resource_price_range import EcommerceV1ProductProductResourcePriceRange
from hostinger_api.models.ecommerce_v1_product_product_resource_variants_inner import EcommerceV1ProductProductResourceVariantsInner
from typing import Optional, Set
from typing_extensions import Self

class EcommerceV1ProductProductResource(BaseModel):
    """
    EcommerceV1ProductProductResource
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="The product ID, required by every other product endpoint.")
    title: Optional[StrictStr] = Field(default=None, description="The product name.")
    status: Optional[StrictStr] = Field(default=None, description="The product status.")
    thumbnail: Optional[StrictStr] = Field(default=None, description="The product's primary image URL, or null.")
    type: Optional[StrictStr] = Field(default=None, description="The product type.")
    variant_count: Optional[StrictInt] = Field(default=None, description="Number of variants. Use include=variants to retrieve them.")
    price_range: Optional[EcommerceV1ProductProductResourcePriceRange] = None
    variants: Optional[List[EcommerceV1ProductProductResourceVariantsInner]] = Field(default=None, description="Present (non-null) only when include=variants is set; null otherwise.")
    media: Optional[List[EcommerceV1ProductProductResourceMediaInner]] = Field(default=None, description="Present (non-null) only when include=media is set; null otherwise.")
    __properties: ClassVar[List[str]] = ["id", "title", "status", "thumbnail", "type", "variant_count", "price_range", "variants", "media"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['draft', 'proposed', 'published', 'rejected', 'archived']):
            raise ValueError("must be one of enum values ('draft', 'proposed', 'published', 'rejected', 'archived')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EcommerceV1ProductProductResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of price_range
        if self.price_range:
            _dict['price_range'] = self.price_range.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in variants (list)
        _items = []
        if self.variants:
            for _item_variants in self.variants:
                if _item_variants:
                    _items.append(_item_variants.to_dict())
            _dict['variants'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in media (list)
        _items = []
        if self.media:
            for _item_media in self.media:
                if _item_media:
                    _items.append(_item_media.to_dict())
            _dict['media'] = _items
        # set to None if thumbnail (nullable) is None
        # and model_fields_set contains the field
        if self.thumbnail is None and "thumbnail" in self.model_fields_set:
            _dict['thumbnail'] = None

        # set to None if variants (nullable) is None
        # and model_fields_set contains the field
        if self.variants is None and "variants" in self.model_fields_set:
            _dict['variants'] = None

        # set to None if media (nullable) is None
        # and model_fields_set contains the field
        if self.media is None and "media" in self.model_fields_set:
            _dict['media'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EcommerceV1ProductProductResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "status": obj.get("status"),
            "thumbnail": obj.get("thumbnail"),
            "type": obj.get("type"),
            "variant_count": obj.get("variant_count"),
            "price_range": EcommerceV1ProductProductResourcePriceRange.from_dict(obj["price_range"]) if obj.get("price_range") is not None else None,
            "variants": [EcommerceV1ProductProductResourceVariantsInner.from_dict(_item) for _item in obj["variants"]] if obj.get("variants") is not None else None,
            "media": [EcommerceV1ProductProductResourceMediaInner.from_dict(_item) for _item in obj["media"]] if obj.get("media") is not None else None
        })
        return _obj


