# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.46.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class EcommerceV1ProductUploadProductImageRequest(BaseModel):
    """
    EcommerceV1ProductUploadProductImageRequest
    """ # noqa: E501
    image_url: Optional[Annotated[str, Field(strict=True, max_length=2048)]] = Field(default=None, description="Publicly reachable URL of the raster image (JPEG, PNG, GIF or WebP), maximum 15MB. The image is fetched, virus-scanned and validated by content, then stored on the CDN. SVG is not accepted. Provide either this or object_name.")
    object_name: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, description="Key returned by the upload-url endpoint. Provide this instead of image_url to attach an uploaded image.")
    is_thumbnail: Optional[StrictBool] = Field(default=None, description="When true, the image becomes the product's thumbnail (primary image). When omitted, it becomes the thumbnail only if the product does not have one yet.")
    __properties: ClassVar[List[str]] = ["image_url", "object_name", "is_thumbnail"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EcommerceV1ProductUploadProductImageRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if is_thumbnail (nullable) is None
        # and model_fields_set contains the field
        if self.is_thumbnail is None and "is_thumbnail" in self.model_fields_set:
            _dict['is_thumbnail'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EcommerceV1ProductUploadProductImageRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "image_url": obj.get("image_url"),
            "object_name": obj.get("object_name"),
            "is_thumbnail": obj.get("is_thumbnail")
        })
        return _obj


