# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.49.3

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class HorizonsV1WebsitesWebsiteResource(BaseModel):
    """
    HorizonsV1WebsitesWebsiteResource
    """ # noqa: E501
    website_id: StrictStr = Field(description="The website ID")
    description: Optional[StrictStr] = Field(default=None, description="The website description")
    domain: Optional[StrictStr] = Field(default=None, description="The domain the website is published on, if it has been published")
    status: StrictStr = Field(description="The website status")
    created_at: datetime = Field(description="The website creation date")
    website_url: StrictStr = Field(description="The website URL for the user to access their website in Hostinger Horizons interface")
    __properties: ClassVar[List[str]] = ["website_id", "description", "domain", "status", "created_at", "website_url"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['active', 'suspended', 'deleting', 'deleted']):
            raise ValueError("must be one of enum values ('active', 'suspended', 'deleting', 'deleted')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HorizonsV1WebsitesWebsiteResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if domain (nullable) is None
        # and model_fields_set contains the field
        if self.domain is None and "domain" in self.model_fields_set:
            _dict['domain'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HorizonsV1WebsitesWebsiteResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "website_id": obj.get("website_id"),
            "description": obj.get("description"),
            "domain": obj.get("domain"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "website_url": obj.get("website_url")
        })
        return _obj


