# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 0.22.1

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class HostingV1WordpressWordpressInstallationResource(BaseModel):
    """
    HostingV1WordpressWordpressInstallationResource
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="WordPress installation (software) id")
    username: Optional[StrictStr] = Field(default=None, description="Hosting account username")
    domain: Optional[StrictStr] = Field(default=None, description="Domain the installation belongs to")
    site_title: Optional[StrictStr] = Field(default=None, description="WordPress site title")
    url: Optional[StrictStr] = Field(default=None, description="WordPress site URL")
    directory: Optional[StrictStr] = Field(default=None, description="Installation directory")
    language: Optional[StrictStr] = Field(default=None, description="WordPress locale")
    login: Optional[StrictStr] = Field(default=None, description="WordPress admin username")
    email: Optional[StrictStr] = Field(default=None, description="WordPress admin email")
    is_valid: Optional[StrictBool] = Field(default=None, description="Whether the installation is considered valid")
    validation_error: Optional[StrictStr] = Field(default=None, description="Reason the installation is invalid, if any")
    created_at: Optional[datetime] = Field(default=None, description="Installation creation timestamp")
    __properties: ClassVar[List[str]] = ["id", "username", "domain", "site_title", "url", "directory", "language", "login", "email", "is_valid", "validation_error", "created_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HostingV1WordpressWordpressInstallationResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if validation_error (nullable) is None
        # and model_fields_set contains the field
        if self.validation_error is None and "validation_error" in self.model_fields_set:
            _dict['validation_error'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HostingV1WordpressWordpressInstallationResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "username": obj.get("username"),
            "domain": obj.get("domain"),
            "site_title": obj.get("site_title"),
            "url": obj.get("url"),
            "directory": obj.get("directory"),
            "language": obj.get("language"),
            "login": obj.get("login"),
            "email": obj.get("email"),
            "is_valid": obj.get("is_valid"),
            "validation_error": obj.get("validation_error"),
            "created_at": obj.get("created_at")
        })
        return _obj


