# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.54.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from hostinger_api.models.hosting_v1_databases_website_database_connection_resource import HostingV1DatabasesWebsiteDatabaseConnectionResource
from typing import Optional, Set
from typing_extensions import Self

class HostingV1DatabasesWebsiteDatabaseResource(BaseModel):
    """
    HostingV1DatabasesWebsiteDatabaseResource
    """ # noqa: E501
    database: HostingV1DatabasesWebsiteDatabaseConnectionResource
    env_var_keys: List[StrictStr] = Field(description="Names of the environment variables written for this database. Values are never returned.")
    __properties: ClassVar[List[str]] = ["database", "env_var_keys"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HostingV1DatabasesWebsiteDatabaseResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of database
        if self.database:
            _dict['database'] = self.database.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HostingV1DatabasesWebsiteDatabaseResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "database": HostingV1DatabasesWebsiteDatabaseConnectionResource.from_dict(obj["database"]) if obj.get("database") is not None else None,
            "env_var_keys": obj.get("env_var_keys")
        })
        return _obj


