# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.32.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from hostinger_api.models.reach_v1_contacts_fields_contact_field_option_resource import ReachV1ContactsFieldsContactFieldOptionResource
from typing import Optional, Set
from typing_extensions import Self

class ReachV1ContactsFieldsContactFieldResource(BaseModel):
    """
    ReachV1ContactsFieldsContactFieldResource
    """ # noqa: E501
    uuid: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    slug: Optional[StrictStr] = Field(default=None, description="Derived from the label on creation and immutable afterwards")
    options: Optional[List[ReachV1ContactsFieldsContactFieldOptionResource]] = Field(default=None, description="Available choices. Always empty for the scalar field types.")
    created_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["uuid", "type", "label", "slug", "options", "created_at"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['text', 'number', 'date', 'single_choice', 'multi_choice']):
            raise ValueError("must be one of enum values ('text', 'number', 'date', 'single_choice', 'multi_choice')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReachV1ContactsFieldsContactFieldResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in options (list)
        _items = []
        if self.options:
            for _item_options in self.options:
                if _item_options:
                    _items.append(_item_options.to_dict())
            _dict['options'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReachV1ContactsFieldsContactFieldResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "type": obj.get("type"),
            "label": obj.get("label"),
            "slug": obj.get("slug"),
            "options": [ReachV1ContactsFieldsContactFieldOptionResource.from_dict(_item) for _item in obj["options"]] if obj.get("options") is not None else None,
            "created_at": obj.get("created_at")
        })
        return _obj


