# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.46.3

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from hostinger_api.models.reach_v1_campaigns_store_request_metadata import ReachV1CampaignsStoreRequestMetadata
from typing import Optional, Set
from typing_extensions import Self

class ReachV1CampaignsStoreRequest(BaseModel):
    """
    Create a campaign in draft status
    """ # noqa: E501
    sender_name: Annotated[str, Field(strict=True, max_length=50)] = Field(description="From name shown to the recipients.")
    sender_email: StrictStr = Field(description="From address of the campaign. Its domain has to be verified on the profile before the campaign can be sent.")
    title: Optional[StrictStr] = Field(default=None, description="Name the campaign is listed under. Not shown to the recipients.")
    subject: Optional[StrictStr] = Field(default=None, description="Subject line of the email.")
    template_uuid: Optional[StrictStr] = Field(default=None, description="Template to send, as returned by the template endpoints. Can be left out and attached later, but the campaign cannot be sent without one.")
    metadata: Optional[ReachV1CampaignsStoreRequestMetadata] = None
    __properties: ClassVar[List[str]] = ["sender_name", "sender_email", "title", "subject", "template_uuid", "metadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReachV1CampaignsStoreRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReachV1CampaignsStoreRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sender_name": obj.get("sender_name"),
            "sender_email": obj.get("sender_email"),
            "title": obj.get("title"),
            "subject": obj.get("subject"),
            "template_uuid": obj.get("template_uuid"),
            "metadata": ReachV1CampaignsStoreRequestMetadata.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None
        })
        return _obj


