# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.47.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ReachV1CampaignsCampaignStatisticsResource(BaseModel):
    """
    Campaign performance. Every count is unique contacts rather than raw events, so a contact who opens the same email five times is counted once.
    """ # noqa: E501
    total_sent: Optional[StrictInt] = Field(default=None, description="Emails sent for this campaign, and the denominator of every rate below.")
    estimated_total_recipients: Optional[StrictInt] = Field(default=None, description="Recipients this campaign was estimated to reach when sending started. Null for campaigns that have not started sending.")
    processed_count: Optional[StrictInt] = None
    delivered_count: Optional[StrictInt] = None
    dropped_count: Optional[StrictInt] = None
    bounced_count: Optional[StrictInt] = None
    soft_bounced_count: Optional[StrictInt] = None
    opened_count: Optional[StrictInt] = Field(default=None, description="Contacts who opened this campaign.")
    clicked_count: Optional[StrictInt] = Field(default=None, description="Contacts who clicked a link. Only clicks from contacts who also registered an open count.")
    unsubscribed_count: Optional[StrictInt] = Field(default=None, description="Contacts who unsubscribed through this campaign.")
    open_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Percentage of sent emails that were opened.")
    click_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Percentage of sent emails that got a click.")
    click_to_open_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Percentage of the contacts who opened that went on to click.")
    unsubscribe_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Percentage of sent emails that led to an unsubscribe.")
    has_bounced_contacts: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["total_sent", "estimated_total_recipients", "processed_count", "delivered_count", "dropped_count", "bounced_count", "soft_bounced_count", "opened_count", "clicked_count", "unsubscribed_count", "open_rate", "click_rate", "click_to_open_rate", "unsubscribe_rate", "has_bounced_contacts"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReachV1CampaignsCampaignStatisticsResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if estimated_total_recipients (nullable) is None
        # and model_fields_set contains the field
        if self.estimated_total_recipients is None and "estimated_total_recipients" in self.model_fields_set:
            _dict['estimated_total_recipients'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReachV1CampaignsCampaignStatisticsResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total_sent": obj.get("total_sent"),
            "estimated_total_recipients": obj.get("estimated_total_recipients"),
            "processed_count": obj.get("processed_count"),
            "delivered_count": obj.get("delivered_count"),
            "dropped_count": obj.get("dropped_count"),
            "bounced_count": obj.get("bounced_count"),
            "soft_bounced_count": obj.get("soft_bounced_count"),
            "opened_count": obj.get("opened_count"),
            "clicked_count": obj.get("clicked_count"),
            "unsubscribed_count": obj.get("unsubscribed_count"),
            "open_rate": obj.get("open_rate"),
            "click_rate": obj.get("click_rate"),
            "click_to_open_rate": obj.get("click_to_open_rate"),
            "unsubscribe_rate": obj.get("unsubscribe_rate"),
            "has_bounced_contacts": obj.get("has_bounced_contacts")
        })
        return _obj


