# coding: utf-8

"""
    Hostinger API Python SDK

    API Version: 1.14.1

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WordPressV1ThemesThemeResource(BaseModel):
    """
    WordPressV1ThemesThemeResource
    """ # noqa: E501
    slug: Optional[StrictStr] = Field(default=None, description="Theme slug used when installing the theme")
    title: Optional[StrictStr] = Field(default=None, description="Human readable theme name")
    url: Optional[StrictStr] = Field(default=None, description="Link to the theme page on WordPress.org")
    featured_image_url: Optional[StrictStr] = Field(default=None, description="URL of the theme preview thumbnail")
    full_image_url: Optional[StrictStr] = Field(default=None, description="URL of the full-size theme preview image")
    description: Optional[StrictStr] = Field(default=None, description="Short theme description")
    logo_url: Optional[StrictStr] = Field(default=None, description="URL of the theme logo")
    is_plan_upgrade_needed: Optional[StrictBool] = Field(default=None, description="Whether a hosting plan upgrade is required to use the theme")
    __properties: ClassVar[List[str]] = ["slug", "title", "url", "featured_image_url", "full_image_url", "description", "logo_url", "is_plan_upgrade_needed"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WordPressV1ThemesThemeResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if featured_image_url (nullable) is None
        # and model_fields_set contains the field
        if self.featured_image_url is None and "featured_image_url" in self.model_fields_set:
            _dict['featured_image_url'] = None

        # set to None if full_image_url (nullable) is None
        # and model_fields_set contains the field
        if self.full_image_url is None and "full_image_url" in self.model_fields_set:
            _dict['full_image_url'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if logo_url (nullable) is None
        # and model_fields_set contains the field
        if self.logo_url is None and "logo_url" in self.model_fields_set:
            _dict['logo_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WordPressV1ThemesThemeResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "slug": obj.get("slug"),
            "title": obj.get("title"),
            "url": obj.get("url"),
            "featured_image_url": obj.get("featured_image_url"),
            "full_image_url": obj.get("full_image_url"),
            "description": obj.get("description"),
            "logo_url": obj.get("logo_url"),
            "is_plan_upgrade_needed": obj.get("is_plan_upgrade_needed")
        })
        return _obj


